export default {
  "Navigation_Home": "Home",
  "Navigation_Search": "Search",
  "Navigation_MyFavorites": "My Favorites",
  "Settings": "Settings",
  "Language_Select": "Language",
  "Serie_DefaultState_Votes": "Votes",
  "Serie_DefaultState_WatchPromo": "Watch Promo",
  "Serie_DefaultState_SeasonSelectLabel": "Seasons",
  "Serie_DefaultState_SeasonTotalEpisodesLabel": "episodes",
  "Serie_DefaultState_ChapterSelectLabel": "Chapters",
  "Serie_DefaultState_FirstAirDate": "First Air Date",
  "Serie_DefaultState_Language": "Language",
  "Serie_DefaultState_Popularity": "Popularity",
  "Serie_ChapterState_Votes": "Votes",
  "Serie_ChapterState_WatchNow": "Watch Now",
  "Serie_ChapterState_AirDate": "Air Date",
  "Serie_ChapterState_Runtime": "Runtime",
  "Serie_ChapterState_EyeMarked": "Marked as watched",
  "Serie_ChapterState_MarkEye": "Mark as watched",
  "Movie_DefaultState_Votes": "Votes",
  "Movie_ChapterState_WatchNow": "Watch Now",
  "Movie_DefaultState_WatchPromo": "Watch Promo",
  "Movie_DefaultState_ReleaseDate": "Release Date",
  "Movie_DefaultState_Language": "Language",
  "Movie_DefaultState_Popularity": "Popularity",
  "AdultContent": "Adult Content",
  "Copyright": "Ptstream. All rights reserved."
}