export default {
  "Movies_Title": "Movies",
  "Series_Title": "Series",
  "Navigation_Home": "Home",
  "Navigation_Search": "Search",
  "Navigation_MyFavorites": "My Favorites",
  "Settings": "Settings",
  "Language_Select": "Language",
  "Serie_DefaultState_Votes": "Votes",
  "Serie_DefaultState_WatchPromo": "Watch Promo",
  "Serie_DefaultState_SeasonSelectLabel": "Seasons",
  "Serie_DefaultState_SeasonTotalEpisodesLabel": "episodes",
  "Serie_DefaultState_ChapterSelectLabel": "Chapters",
  "Serie_DefaultState_FirstAirDate": "First Air Date",
  "Serie_DefaultState_Language": "Language",
  "Serie_DefaultState_Popularity": "Popularity",
  "Serie_ChapterState_Votes": "Votes",
  "Serie_ChapterState_WatchNow": "Watch Now",
  "Serie_ChapterState_AirDate": "Air Date",
  "Serie_ChapterState_Runtime": "Runtime",
  "Serie_ChapterState_EyeMarked": "Marked as watched",
  "Serie_ChapterState_MarkEye": "Mark as watched",
  "Serie_EmptyState_Text1": "No series found",
  "Movie_DefaultState_Votes": "Votes",
  "Movie_ChapterState_WatchNow": "Watch Now",
  "Movie_DefaultState_WatchPromo": "Watch Promo",
  "Movie_DefaultState_ReleaseDate": "Release Date",
  "Movie_DefaultState_Language": "Language",
  "Movie_DefaultState_Popularity": "Popularity",
  "Movie_EmptyState_Text1": "No movies found",
  "Search_DefaultState_Text1": "Start your search",
  "Search_DefaultState_Text2": "Find what you're looking for by searching our extensive database of movies and series.",
  "Search_DefaultState_Text3": "Try searching for:",
  "Search_TableContent_Input_Placeholder": "Search by name...",
  "Search_TableContent_MediaTypeSerie": "Series",
  "Search_TableContent_MediaTypeMovie": "Movie",
  "MyFavorites_DefaultState_Text1": " Discover Your Favorite Movies & Series",
  "MyFavorites_DefaultState_Text2": "You haven't added any favorite movies or series yet. Start by searching our extensive database and find your next favorite.",
  "MyFavorites_DefaultState_Text3": "Need inspiration? Try searching for:",
  "MyFavorites_FilterEmptyState": "No favorites found",
  "AdultContent": "Adult Content",
  "Copyright": "Ptstream. All rights reserved.",
  "28": "Action",
  "12": "Adventure",
  "16": "Animation",
  "35": "Comedy",
  "80": "Crime",
  "99": "Documentary",
  "18": "Drama",
  "10751": "Family",
  "14": "Fantasy",
  "36": "History",
  "27": "Horror",
  "10402": "Music",
  "9648": "Mystery",
  "10749": "Romance",
  "878": "Science Fiction",
  "10770": "TV Movie",
  "53": "Thriller",
  "10752": "War",
  "37": "Western",
  "0": "Reset",
  "10759": "Action & Adventure",
  "10762": "Kids",
  "10763": "News",
  "10764": "Reality",
  "10765": "Sci-Fi & Fantasy",
  "10766": "Soap",
  "10767": "Talk",
  "10768": "War & Politics",
  "Scene_NotFound": "Scene not found.",
}