export default {
  "Navigation_Home": "Home",
  "Navigation_Search": "Search",
  "Navigation_MyFavorites": "My Favorites",
  "Settings": "Settings",
  "Language_Select": "Language",
  "Serie_DefaultState_Votes": "Votes",
  "Serie_DefaultState_WatchPromo": "Watch Promo",
  "Serie_DefaultState_SeasonSelectLabel": "Seasons",
  "Serie_DefaultState_SeasonTotalEpisodesLabel": "episodes",
  "Serie_DefaultState_ChapterSelectLabel": "Chapters",
  "Serie_DefaultState_FirstAirDate": "First Air Date",
  "Serie_DefaultState_Language": "Language",
  "Serie_DefaultState_Popularity": "Popularity",
  "Serie_ChapterState_Votes": "Votes",
  "Serie_ChapterState_WatchNow": "Watch Now",
  "Serie_ChapterState_AirDate": "Air Date",
  "Serie_ChapterState_Runtime": "Runtime",
  "Serie_ChapterState_EyeMarked": "Marked as watched",
  "Serie_ChapterState_MarkEye": "Mark as watched",
  "Movie_DefaultState_Votes": "Votes",
  "Movie_ChapterState_WatchNow": "Watch Now",
  "Movie_DefaultState_WatchPromo": "Watch Promo",
  "Movie_DefaultState_ReleaseDate": "Release Date",
  "Movie_DefaultState_Language": "Language",
  "Movie_DefaultState_Popularity": "Popularity",
  "AdultContent": "Adult Content",
  "Copyright": "Ptstream. All rights reserved.",
  "28": "Action",
  "12": "Adventure",
  "16": "Animation",
  "35": "Comedy",
  "80": "Crime",
  "99": "Documentary",
  "18": "Drama",
  "10751": "Family",
  "14": "Fantasy",
  "36": "History",
  "27": "Horror",
  "10402": "Music",
  "9648": "Mystery",
  "10749": "Romance",
  "878": "Science Fiction",
  "10770": "TV Movie",
  "53": "Thriller",
  "10752": "War",
  "37": "Western",
  "0": "Reset",
  "10759": "Action & Adventure",
  "10762": "Kids",
  "10763": "News",
  "10764": "Reality",
  "10765": "Sci-Fi & Fantasy",
  "10766": "Soap",
  "10767": "Talk",
  "10768": "War & Politics",
}