export default {
  "Navigation_Home": "Startseite",
  "Navigation_Search": "Suche",
  "Navigation_MyFavorites": "Meine Favoriten",
  "Settings": "Einstellungen",
  "Language_Select": "Sprache",
  "Serie_DefaultState_Votes": "Stimmen",
  "Serie_DefaultState_WatchPromo": "Promo ansehen",
  "Serie_DefaultState_SeasonSelectLabel": "Staffeln",
  "Serie_DefaultState_SeasonTotalEpisodesLabel": "Episoden",
  "Serie_DefaultState_ChapterSelectLabel": "Kapitel",
  "Serie_DefaultState_FirstAirDate": "Erstausstrahlungsdatum",
  "Serie_DefaultState_Language": "Sprache",
  "Serie_DefaultState_Popularity": "Beliebtheit",
  "Serie_ChapterState_Votes": "Stimmen",
  "Serie_ChapterState_WatchNow": "Jetzt ansehen",
  "Serie_ChapterState_AirDate": "Ausstrahlungsdatum",
  "Serie_ChapterState_Runtime": "Laufzeit",
  "Serie_ChapterState_EyeMarked": "Als gesehen markiert",
  "Serie_ChapterState_MarkEye": "Als gesehen markieren",
  "Serie_EmptyState_Text1": "Keine Serien gefunden",
  "Movie_DefaultState_Votes": "Stimmen",
  "Movie_ChapterState_WatchNow": "Jetzt ansehen",
  "Movie_DefaultState_WatchPromo": "Promo ansehen",
  "Movie_DefaultState_ReleaseDate": "Veröffentlichungsdatum",
  "Movie_DefaultState_Language": "Sprache",
  "Movie_DefaultState_Popularity": "Beliebtheit",
  "Movie_EmptyState_Text1": "Keine Filme gefunden",
  "Search_DefaultState_Text1": "Beginne deine Suche",
  "Search_DefaultState_Text2": "Finde, wonach du suchst, indem du unsere umfangreiche Datenbank nach Filmen und Serien durchsuchst.",
  "Search_DefaultState_Text3": "Versuche zu suchen nach:",
  "Search_TableContent_Input_Placeholder": "Suche nach Name...",
  "Search_TableContent_MediaTypeSerie": "Serie",
  "Search_TableContent_MediaTypeMovie": "Film",
  "MyFavorites_DefaultState_Text1": "Entdecke deine Lieblingsfilme & Serien",
  "MyFavorites_DefaultState_Text2": "Du hast noch keine Lieblingsfilme oder -serien hinzugefügt. Beginne, indem du unsere umfangreiche Datenbank durchsuchst und deine nächste Favoriten findest.",
  "MyFavorites_DefaultState_Text3": "Brauchst du Inspiration? Versuche zu suchen nach:",
  "MyFavorites_FilterEmptyState": "Keine Favoriten gefunden",
  "AdultContent": "Inhalte für Erwachsene",
  "Copyright": "Ptstream. Alle Rechte vorbehalten.",
  "28": "Action",
  "12": "Abenteuer",
  "16": "Animation",
  "35": "Komödie",
  "80": "Krimi",
  "99": "Dokumentation",
  "18": "Drama",
  "10751": "Familie",
  "14": "Fantasy",
  "36": "Geschichte",
  "27": "Horror",
  "10402": "Musik",
  "9648": "Mystery",
  "10749": "Romanze",
  "878": "Science-Fiction",
  "10770": "TV-Film",
  "53": "Thriller",
  "10752": "Krieg",
  "37": "Western",
  "0": "Zurücksetzen",
  "10759": "Action & Abenteuer",
  "10762": "Kinder",
  "10763": "Nachrichten",
  "10764": "Reality-TV",
  "10765": "Sci-Fi & Fantasy",
  "10766": "Seifenoper",
  "10767": "Talkshow",
  "10768": "Krieg & Politik",
  "Scene_NotFound": "Szene nicht gefunden.",
}