export default {
  "Navigation_Home": "Inicio",
  "Navigation_Search": "Buscar",
  "Navigation_MyFavorites": "Mis Favoritos",
  "Settings": "Ajustes",
  "Language_Select": "Idioma",
  "Serie_DefaultState_Votes": "Votos",
  "Serie_DefaultState_WatchPromo": "Ver Promo",
  "Serie_DefaultState_SeasonSelectLabel": "Temporadas",
  "Serie_DefaultState_SeasonTotalEpisodesLabel": "episodios",
  "Serie_DefaultState_ChapterSelectLabel": "Capítulos",
  "Serie_DefaultState_FirstAirDate": "Fecha de Estreno",
  "Serie_DefaultState_Language": "Idioma",
  "Serie_DefaultState_Popularity": "Popularidad",
  "Serie_ChapterState_Votes": "Votos",
  "Serie_ChapterState_WatchNow": "Ver Ahora",
  "Serie_ChapterState_AirDate": "Fecha de Emisión",
  "Serie_ChapterState_Runtime": "Duración",
  "Serie_ChapterState_EyeMarked": "Marcado como visto",
  "Serie_ChapterState_MarkEye": "Marcar como visto",
  "Movie_DefaultState_Votes": "Votos",
  "Movie_ChapterState_WatchNow": "Ver Ahora",
  "Movie_DefaultState_WatchPromo": "Ver Promo",
  "Movie_DefaultState_ReleaseDate": "Fecha de estreno",
  "Movie_DefaultState_Language": "Idioma",
  "Movie_DefaultState_Popularity": "Popularidad",
  "AdultContent": "Contenido Para Adultos",
  "Copyright": "Ptstream. Todos los derechos reservados."
}