export default {
  "Navigation_Home": "Inicio",
  "Navigation_Search": "Buscar",
  "Navigation_MyFavorites": "Mis Favoritos",
  "Settings": "Ajustes",
  "Language_Select": "Idioma",
  "Serie_DefaultState_Votes": "Votos",
  "Serie_DefaultState_WatchPromo": "Ver Promo",
  "Serie_DefaultState_SeasonSelectLabel": "Temporadas",
  "Serie_DefaultState_SeasonTotalEpisodesLabel": "episodios",
  "Serie_DefaultState_ChapterSelectLabel": "Capítulos",
  "Serie_DefaultState_FirstAirDate": "Fecha de Estreno",
  "Serie_DefaultState_Language": "Idioma",
  "Serie_DefaultState_Popularity": "Popularidad",
  "Serie_ChapterState_Votes": "Votos",
  "Serie_ChapterState_WatchNow": "Ver Ahora",
  "Serie_ChapterState_AirDate": "Fecha de Emisión",
  "Serie_ChapterState_Runtime": "Duración",
  "Serie_ChapterState_EyeMarked": "Marcado como visto",
  "Serie_ChapterState_MarkEye": "Marcar como visto",
  "Movie_DefaultState_Votes": "Votos",
  "Movie_ChapterState_WatchNow": "Ver Ahora",
  "Movie_DefaultState_WatchPromo": "Ver Promo",
  "Movie_DefaultState_ReleaseDate": "Fecha de estreno",
  "Movie_DefaultState_Language": "Idioma",
  "Movie_DefaultState_Popularity": "Popularidad",
  "AdultContent": "Contenido Para Adultos",
  "Copyright": "Ptstream. Todos los derechos reservados.",
  "28": "Acción",
  "12": "Aventura",
  "16": "Animación",
  "35": "Comedia",
  "80": "Crimen",
  "99": "Documental",
  "18": "Drama",
  "10751": "Familia",
  "14": "Fantasía",
  "36": "Historia",
  "27": "Terror",
  "10402": "Música",
  "9648": "Misterio",
  "10749": "Romance",
  "878": "Ciencia Ficción",
  "10770": "Película para Televisión",
  "53": "Thriller",
  "10752": "Guerra",
  "37": "Western",
  "0": "Reiniciar",
  "10759": "Acción y Aventura",
  "10762": "Niños",
  "10763": "Noticias",
  "10764": "Reality",
  "10765": "Ciencia Ficción y Fantasía",
  "10766": "Telenovela",
  "10767": "Charlas",
  "10768": "Guerra y Política"
}