export default {
  "Navigation_Home": "Accueil",
  "Navigation_Search": "Rechercher",
  "Navigation_MyFavorites": "Mes Favoris",
  "Settings": "Paramètres",
  "Language_Select": "Langue",
  "Serie_DefaultState_Votes": "Votes",
  "Serie_DefaultState_WatchPromo": "Voir la promo",
  "Serie_DefaultState_SeasonSelectLabel": "Saisons",
  "Serie_DefaultState_SeasonTotalEpisodesLabel": "épisodes",
  "Serie_DefaultState_ChapterSelectLabel": "Chapitres",
  "Serie_DefaultState_FirstAirDate": "Date de sortie",
  "Serie_DefaultState_Language": "Langue",
  "Serie_DefaultState_Popularity": "Popularité",
  "Serie_ChapterState_Votes": "Votes",
  "Serie_ChapterState_WatchNow": "Regarder maintenant",
  "Serie_ChapterState_AirDate": "Date de diffusion",
  "Serie_ChapterState_Runtime": "Durée",
  "Serie_ChapterState_EyeMarked": "Marqué comme vu",
  "Serie_ChapterState_MarkEye": "Marquer comme vu",
  "Serie_EmptyState_Text1": "Aucune série trouvée",
  "Movie_DefaultState_Votes": "Votes",
  "Movie_ChapterState_WatchNow": "Regarder maintenant",
  "Movie_DefaultState_WatchPromo": "Voir la promo",
  "Movie_DefaultState_ReleaseDate": "Date de sortie",
  "Movie_DefaultState_Language": "Langue",
  "Movie_DefaultState_Popularity": "Popularité",
  "Movie_EmptyState_Text1": "Aucun film trouvé",
  "Search_DefaultState_Text1": "Commencez votre recherche",
  "Search_DefaultState_Text2": "Trouvez ce que vous cherchez en explorant notre vaste base de données de films et de séries.",
  "Search_DefaultState_Text3": "Essayez de rechercher :",
  "Search_TableContent_Input_Placeholder": "Rechercher par nom...",
  "MyFavorites_DefaultState_Text1": "Découvrez vos films et séries préférés",
  "MyFavorites_DefaultState_Text2": "Vous n'avez pas encore ajouté de film ou de série à vos favoris. Commencez à chercher dans notre vaste base de données et trouvez votre prochain coup de cœur.",
  "MyFavorites_DefaultState_Text3": "Besoin d'inspiration ? Essayez de rechercher :",
  "MyFavorites_FilterEmptyState": "Aucun favori trouvé",
  "AdultContent": "Contenu pour adultes",
  "Copyright": "Ptstream. Tous droits réservés.",
  "28": "Action",
  "12": "Aventure",
  "16": "Animation",
  "35": "Comédie",
  "80": "Crime",
  "99": "Documentaire",
  "18": "Drame",
  "10751": "Famille",
  "14": "Fantastique",
  "36": "Histoire",
  "27": "Horreur",
  "10402": "Musique",
  "9648": "Mystère",
  "10749": "Romance",
  "878": "Science-fiction",
  "10770":
    "Téléfilm",
  "53": "Thriller",
  "10752": "Guerre",
  "37": "Western",
  "0": "Réinitialiser",
  "10759": "Action et aventure",
  "10762": "Enfants",
  "10763": "Actualités",
  "10764": "Réalité",
  "10765": "Science-fiction et fantastique",
  "10766": "Telenovela",
  "10767": "Talk-show",
  "10768": "Guerre et politique"
}